---
- name: debian | ensuring rsyslog is installed
  apt:
    name: rsyslog
    state: present

- name: debian | configuring rsyslog.conf
  template:
    src: "etc/rsyslog.conf.j2"
    dest: "/etc/rsyslog.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
  when: configure_rsyslog is defined and configure_rsyslog

- name: debian | configuring rsyslog
  template:
    src: "etc/rsyslog.d/50-default.conf.j2"
    dest: "/etc/rsyslog.d/50-default.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
  when: configure_rsyslog is defined and configure_rsyslog
