---
# tasks file for ansible-openstack
- include: openstack_basic.yml

- include: openstack_rabbitmq_config.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_identity_services.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_tenants.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_users.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_roles.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_services.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_endpoints.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_image_services.yml
  when: inventory_hostname in groups['openstack-controller-nodes']
