---
# tasks file for ansible-openstack
- include: openstack_basic.yml

- include: openstack_haproxy_config.yml
  when: (openstack_haproxy_config is defined and openstack_haproxy_config) and inventory_hostname in groups['openstack-haproxy-nodes']

- include: openstack_rabbitmq_config.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_identity_services.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_tenants.yml  #Tenants are now projects
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_users.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_roles.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_services.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_keystone_endpoints.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_image_services.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_compute_services.yml
  when: inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_compute.yml
  when: inventory_hostname in groups['openstack-compute-nodes']

- include: openstack_neutron_controller_nodes.yml
  when: openstack_networking  == "neutron" and inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_neutron_network_nodes.yml
  when: openstack_networking  == "neutron" and inventory_hostname in groups['openstack-network-nodes']

- include: openstack_neutron_compute_nodes.yml
  when: openstack_networking  == "neutron" and inventory_hostname in groups['openstack-compute-nodes']

- include: openstack_neutron_manage_external_networks.yml
  tags:
    - create_neutron_external_networks
    - neutron_networks
  when: (config_openstack_neutron_networks is defined and config_openstack_neutron_networks) and openstack_networking  == "neutron" and inventory_hostname in groups['openstack-controller-nodes']

- include: openstack_neutron_manage_tenant_networks.yml
  tags:
    - create_neutron_tenant_networks
    - neutron_networks
  when: (config_openstack_neutron_networks is defined and config_openstack_neutron_networks) and openstack_networking  == "neutron" and inventory_hostname in groups['openstack-controller-nodes']
