---
- name: openstack_rabbitmq_config | creating RabbitMQ user
  rabbitmq_user:
    user: "{{ openstack_rabbit_user }}"
    password: "{{ openstack_rabbit_pass }}"
    vhost: "/"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: present
  when: (openstack_multi_controller_setup is defined and not openstack_multi_controller_setup) or openstack_multi_controller_setup is not defined

- name: openstack_rabbitmq_config | creating RabbitMQ user
  rabbitmq_user:
    user: "{{ openstack_rabbit_user }}"
    password: "{{ openstack_rabbit_pass }}"
    vhost: "/"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: present
  when: openstack_multi_controller_setup is defined and openstack_multi_controller_setup
