---
- name: openstack_keystone_tenants | creating tenants
  keystone_user:
    tenant: "{{ item.name }}"
    tenant_description: "{{ item.description }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_tenants
  when: openstack_keystone_api_master is defined and (inventory_hostname == openstack_keystone_api_master)

- name: openstack_keystone_tenants | creating tenants  #duplicated to ensure that if openstack_keystone_api_master does not match an inventory_hostname
  keystone_user:
    tenant: "{{ item.name }}"
    tenant_description: "{{ item.description }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_tenants
  when: openstack_keystone_api_master is defined and (inventory_hostname != openstack_keystone_api_master)
