---
- name: openstack_neutron_create_tenant_networks | creating tenant network(s)
  neutron_network:
    login_tenant_name: "{{ item.tenant_name }}"
    login_username: "{{ item.username }}"
    login_password: "{{ item.password }}"
    name: "{{ item.network_name }}"
    state: present
  with_items: openstack_neutron_tenant_network_info
  when: item.network_name is defined

- name: openstack_neutron_create_tenant_networks | creating tenant subnet(s)
  neutron_subnet:
    login_tenant_name: "{{ item.tenant_name }}"
    login_username: "{{ item.username }}"
    login_password: "{{ item.password }}"
    name: "{{ item.subnet_name }}"
    network_name: "{{ item.network_name }}"
    cidr: "{{ item.cidr }}"
    gateway_ip: "{{ item.gateway }}"
    state: present
  with_items: openstack_neutron_tenant_network_info
  when: item.subnet_name is defined

- name: openstack_neutron_create_tenant_networks | creating tenant router(s)
  neutron_router:
    login_tenant_name: "{{ item.tenant_name }}"
    login_username: "{{ item.username }}"
    login_password: "{{ item.password }}"
    name: "{{ item.router_name }}"
    state: present
  with_items: openstack_neutron_tenant_network_info
  when: item.router_name is defined

- name: openstack_neutron_create_tenant_networks | creating tenant router(s) interfaces
  neutron_router_interface:
    login_tenant_name: "{{ item.tenant_name }}"
    login_username: "{{ item.username }}"
    login_password: "{{ item.password }}"
    router_name: "{{ item.router_name }}"
    subnet_name: "{{ item.subnet_name }}"
    state: present
  with_items: openstack_neutron_tenant_network_info
  when: item.router_name is defined
