---
- name: openstack_horizon | Installing Horizon Dashboard
  apt:
    name: "openstack-dashboard"
    state: "present"

- name: openstack_horizon | Configuring Horizon
  template:
    src: "etc/openstack-dashboard/local_settings.py.j2"
    dest: "/etc/openstack-dashboard/local_settings.py"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - restart apache2

- name: openstack_horizon | Removing Ubuntu Horizon Theme
  apt:
    name: "openstack-dashboard-ubuntu-theme"
    state: "absent"
  tags:
    - "uninstall_ubuntu_horizon_dashboard"
  when: >
        openstack_horizon_remove_ubuntu_theme is defined and
        openstack_horizon_remove_ubuntu_theme

- name: openstack_horizon | Installing Ubuntu Horizon Theme
  apt:
    name: "openstack-dashboard-ubuntu-theme"
    state: "present"
  tags:
    - "install_ubuntu_horizon_dashboard"
  when: >
        (openstack_horizon_remove_ubuntu_theme is defined and
        not openstack_horizon_remove_ubuntu_theme) or
        openstack_horizon_remove_ubuntu_theme is not defined
