---
# Basic Environment Configurations
- name: openstack_basic | restarting mysql
  service:
    name: mysql
    state: restarted
  ignore_errors: yes

- name: openstack_basic | cleaning up ntp dhcp configurations
  file:
    path: /var/lib/ntp/ntp.conf.dhcp
    state: absent

- name: openstack_basic | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ubuntu-cloud-keyring

- name: openstack_basic | adding openstack debian repos
  apt_repository:
    repo: "{{ openstack_debian_repository }}"
    state: present

- name: openstack_basic | updated /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_ssh_host }}"
    line: "{{ hostvars[item].ansible_ssh_host }}    {{ hostvars[item].inventory_hostname }}"
  with_items: groups['all']
