---
- name: openstack_keystone_users | creating users
  keystone_user:
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    email: "{{ item.email|default('nobody@localhost') }}"
    tenant: "{{ item.tenant }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_users
  when: >
        openstack_keystone_api_master is defined and
        (inventory_hostname == openstack_keystone_api_master)

- name: openstack_keystone_users | creating users  #duplicated to ensure that if openstack_keystone_api_master does not match an inventory_hostname
  keystone_user:
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    email: "{{ item.email|default('nobody@localhost') }}"
    tenant: "{{ item.tenant }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_users
  when: >
        openstack_keystone_api_master is defined and
        (inventory_hostname != openstack_keystone_api_master)
