---
- name: openstack_basic | Cleaning Up NTP DHCP Configurations
  file:
    path: "/var/lib/ntp/ntp.conf.dhcp"
    state: "absent"

- name: openstack_basic | Installing Pre-Reqs
  apt:
    name: "ubuntu-cloud-keyring"
    state: "present"

- name: openstack_basic | Adding OpenStack Debian Repos
  apt_repository:
    repo: "{{ openstack_debian_repository }}"
    state: "present"

- name: openstack_basic | Configuring System To Allow VIP To Come UP
  sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: 1
    state: "present"
    reload: yes
  when: >
        (openstack_haproxy_config is defined and
        openstack_haproxy_config) and
        (inventory_hostname in groups['openstack-controller-nodes'] or
        inventory_hostname in groups['openstack-haproxy-nodes'])
