---
# Basic Environment Configurations
- name: openstack_basic | cleaning up ntp dhcp configurations
  file:
    path: /var/lib/ntp/ntp.conf.dhcp
    state: absent

- name: openstack_basic | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ubuntu-cloud-keyring

- name: openstack_basic | adding openstack debian repos
  apt_repository:
    repo: "{{ openstack_debian_repository }}"
    state: present
