---
- name: openstack_identity_services | creating tenants
  keystone_user:
    tenant: "{{ item.name }}"
    tenant_description: "{{ item.description }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_tenants
  when: (openstack_multi_controller_setup is defined and not openstack_multi_controller_setup) or openstack_multi_controller_setup is not defined

- name: openstack_identity_services | creating tenants
  keystone_user:
    tenant: "{{ item.name }}"
    tenant_description: "{{ item.description }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  run_once: yes
  with_items: openstack_keystone_tenants
  when: openstack_multi_controller_setup is defined and openstack_multi_controller_setup
