---
- name: openstack_neutron_create_external_networks | creating default external network
  neutron_network:
#    auth_url: "{{ openstack_keystone_url }}:35357/v2.0/"
    login_tenant_name: admin
    login_username: admin
    login_password: "{{ openstack_admin_pass }}"
    name: "{{ item.network_name }}"
    provider_network_type: "{{ item.provider_network_type }}"
    provider_physical_network: "{{ item.provider_physical_network }}"
    router_external: "{{ item.router_external }}"
    shared: "{{ item.shared }}"
    state: present
  with_items: openstack_neutron_external_network_info

- name: openstack_neutron_create_external_networks | creating default external subnet
  neutron_subnet:
#    auth_url: "{{ openstack_keystone_url }}:35357/v2.0/"
    login_tenant_name: admin
    login_username: admin
    login_password: "{{ openstack_admin_pass }}"
    name: "{{ item.subnet_name }}"
    network_name: "{{ item.network_name }}"
    cidr: "{{ item.cidr }}"
    enable_dhcp: "{{ item.enable_dhcp }}"
    gateway_ip: "{{ item.gateway }}"
    allocation_pool_start: "{{ item.pool_start }}"
    allocation_pool_end: "{{ item.pool_end }}"
    state: present
  with_items: openstack_neutron_external_network_info
