---
- name: openstack_identity_services | creating keystone services
  keystone_service:
    name: "{{ item.name }}"
    service_type: "{{ item.service_type }}"
    description: "{{ item.description|default('Not provided') }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_services
