---
- name: openstack_identity_services | creating users
  keystone_user:
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    email: "{{ item.email|default('nobody@localhost') }}"
    tenant: "{{ item.tenant }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_users
