---
- name: openstack_keystone_services | creating keystone services
  keystone_service:
    name: "{{ item.name }}"
    service_type: "{{ item.service_type }}"
    description: "{{ item.description|default('Not provided') }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_services
  when: >
        openstack_keystone_api_master is defined and
        (inventory_hostname == openstack_keystone_api_master)

- name: openstack_keystone_services | creating keystone services  #duplicated to ensure that if openstack_keystone_api_master does not match an inventory_hostname
  keystone_service:
    name: "{{ item.name }}"
    service_type: "{{ item.service_type }}"
    description: "{{ item.description|default('Not provided') }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_services
  when: >
        openstack_keystone_api_master is defined and
        (inventory_hostname != openstack_keystone_api_master)
