---
- name: openstack_identity_services | creating tenants
  keystone_user:
    tenant: "{{ item.name }}"
    tenant_description: "{{ item.description }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_tenants
