---
# Sets up and configures identity services for OpenStack
# http://docs.openstack.org/juno/install-guide/install/apt/content/ch_keystone.html
- name: openstack_identity_services | creating Keystone DB
  mysql_db:
    name: keystone
    state: present

- name: openstack_identity_services | granting permissions to Keystone DB
  mysql_user:
    name: keystone
    password: "{{ openstack_keystone_dbpass }}"
    priv: "keystone.*:ALL"
    host: "{{ item }}"
    state: present
  with_items:
    - localhost
    - '%'

- name: openstack_identity_services | marking keystone to not auto start after install
  shell: 'echo "manual" > /etc/init/keystone.override'
  args:
    creates: /etc/init/keystone.override

- name: openstack_identity_services | installing keystone packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - keystone
    - libapache2-mod-wsgi
    - python-keystoneclient
    - python-memcache
    - python-openstackclient

- name: openstack_identity_services | configuring keystone
  template:
    src: etc/keystone/keystone.conf.j2
    dest: /etc/keystone/keystone.conf
    owner: root
    group: root
    mode: 0644
#  notify: restart keystone

- name: openstack_identity_services | checking if keystone has been populated
  stat:
    path: /etc/keystone/keystone_populated
  register: keystone_is_populated

- name: openstack_identity_services | populating keystone
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone
  register: keystone_populated
  when: not keystone_is_populated.stat.exists

- name: openstack_identity_services | marking keystone as populated
  file:
    path: /etc/keystone/keystone_populated
    state: touch
  when: keystone_populated.changed

- name: openstack_identity_services | disabling default apache site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - restart apache2

- name: openstack_identity_services | configuring apache
  lineinfile:
    dest: "/etc/apache2/apache2.conf"
    line: "ServerName {{ inventory_hostname }}"
  notify:
    - restart apache2

- name: openstack_identity_services | configuring identity service virtual hosts
  template:
    src: etc/apache2/sites-available/wsgi-keystone.conf.j2
    dest: /etc/apache2/sites-available/wsgi-keystone.conf
    owner: root
    group: root
    mode: 0644

- name: openstack_identity_services | enabling identity service virtual hosts
  file:
    src: /etc/apache2/sites-available/wsgi-keystone.conf
    dest: /etc/apache2/sites-enabled/wsgi-keystone.conf
    state: link
  register: apache2_reconfigured
  notify:
    - restart apache2

- name: openstack_identity_services | creating WSGI components folder
  file:
    path: /var/www/cgi-bin/keystone
    state: directory

- name: openstack_identity_services | downloading WSGI components
  get_url:
    url: http://git.openstack.org/cgit/openstack/keystone/plain/httpd/keystone.py?h=stable/kilo
    dest: "{{ item }}"
  with_items:
    - /var/www/cgi-bin/keystone/main
    - /var/www/cgi-bin/keystone/admin

- name: openstack_identity_services | setting permissions on WSGI folder(s)
  file:
    path: /var/www/cgi-bin/keystone
    owner: keystone
    group: keystone
    mode: 0755
    recurse: yes

#- name: openstack_identity_services | restarting keystone
#  service:
#    name: keystone
#    state: restarted
#  when: keystone_populated.changed

- name: openstack_identity_services | restarting apache2
  service:
    name: apache2
    state: restarted
  when: apache2_reconfigured.changed

- name: openstack_identity_services | removing sqlite db
  file:
    path: /var/lib/keystone/keystone.db
    state: absent

- name: openstack_identity_services | creating cron job to clean expired tokens
  cron:
    name: "keystone token flush"
    special_time: hourly
    user: keystone
    job: "/usr/bin/keystone-manage token_flush >/var/log/keystone/keystone-tokenflush.log 2>&1"
    state: present
    cron_file: keystone_token_flush
