---
- name: openstack_keystone_endpoints | creating keystone endpoints
  keystone_endpoint:
    service_name: "{{ item.service_name }}"
    region: "{{ item.region|default(openstack_keystone_default_region) }}"
    public_url: "{{ item.public_url }}"
    internal_url: "{{ item.internal_url }}"
    admin_url: "{{ item.admin_url }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_endpoints
  when: openstack_keystone_api_master is defined and (inventory_hostname == openstack_keystone_api_master)

- name: openstack_keystone_endpoints | creating keystone endpoints  #duplicated to ensure that if openstack_keystone_api_master does not match an inventory_hostname
  keystone_endpoint:
    service_name: "{{ item.service_name }}"
    region: "{{ item.region|default(openstack_keystone_default_region) }}"
    public_url: "{{ item.public_url }}"
    internal_url: "{{ item.internal_url }}"
    admin_url: "{{ item.admin_url }}"
    token: "{{ openstack_keystone_temp_admin_token }}"
    state: present
  with_items: openstack_keystone_endpoints
  when: openstack_keystone_api_master is defined and (inventory_hostname != openstack_keystone_api_master)
