---
# - name: openstack_neutron_compute_nodes | Setting Kernel Networking Parameters
#   sysctl:
#     name: "{{ item.name }}"
#     value: "{{ item.value }}"
#     state: "present"
#     reload: yes
#   with_items:
#     - name: 'net.ipv4.conf.all.rp_filter'
#       value: 0
#     - name: 'net.ipv4.conf.default.rp_filter'
#       value: 0
# #    - name: net.bridge.bridge-nf-call-iptables
# #      value: 1
# #    - name: net.bridge.bridge-nf-call-ip6tables
# #      value: 1

- name: openstack_neutron_compute_nodes | Installing Neutron Packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'conntrack'
    - 'neutron-plugin-linuxbridge-agent'
    # - neutron-plugin-ml2
    # - neutron-plugin-openvswitch-agent

- name: openstack_neutron_compute_nodes | Configuring Neutron
  template:
    src: "etc/neutron/neutron.conf.j2"
    dest: "/etc/neutron/neutron.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - "restart neutron-plugin-linuxbridge-agent"
    # - "restart openvswitch-switch"
    # - "restart neutron-plugin-openvswitch-agent"

- name: openstack_neutron_compute_nodes | Configuring Neutron ML2 Plugin(s)
  template:
    src: etc/neutron/plugins/ml2/ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - "restart neutron-plugin-linuxbridge-agent"
    # - "restart openvswitch-switch"
    # - "restart neutron-plugin-openvswitch-agent"

- name: openstack_neutron_compute_nodes | Configuring Neutron ML2 Plugin(s)
  template:
    src: "etc/neutron/plugins/ml2/linuxbridge_agent.ini.j2"
    dest: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - "restart neutron-plugin-linuxbridge-agent"

- name: openstack_neutron_compute_nodes | Configuring Nova
  template:
    src: "etc/nova/nova.conf.j2"
    dest: "/etc/nova/nova.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - "restart nova-compute"
    # - "restart neutron-plugin-openvswitch-agent"
