---
# handlers file for ansible-openstack
- name: restart glance-api
  service:
    name: glance-api
    state: restarted

- name: restart glance-registry
  service:
    name: glance-registry
    state: restarted

- name: restart keystone
  service:
    name: keystone
    state: restarted
