---
- name: ferm | ensuring ferm is installed (Debian)
  apt:
    name: ferm
    state: present
  when: ansible_os_family == "Debian"

- name: ferm | ensuring ferm is installed (RedHat)
  yum:
    name: ferm
    state: present
  when: ansible_os_family == "RedHat"

- name: ferm | ensuring ferm is started and enabled
  service:
    name: ferm
    state: started
    enabled: yes

- name: ferm | configuring firewall for elasticsearch
  copy:
    dest: /etc/ferm/ferm.d/20-elasticsearch.conf
    src: 20-elasticsearch.conf
    owner: root
    group: root
    mode: 0700
  notify: run ferm
