---
- name: nfs | installing debian nfs client
  apt:
    name: nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: nfs | installing centos nfs client
  yum:
    name: nfs-common
    state: present
  when: ansible_os_family == "RedHat"

- name: nfs | mounting nfs volume
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.mount }}"
    fstype: nfs
    opts: "{{ item.opts }}"
    state: mounted
  with_items: es_nfs
