---
# handlers file for ansible-elasticsearch
- name: init elasticsearch
  command: update-rc.d elasticsearch defaults 95 10

- name: restart elasticsearch
  service: name=elasticsearch state=restarted
